ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080

database:
  url: "jdbc:sqlite:data.db"
  driver: "org.sqlite.JDBC"

jwt:
  realm: "Ktor Testiipii"
  secret: "top-sicret-key"
  issuer: "ktor-test-api"
  audience: "postman-client"
